---

plugins:
  # https://github.com/jest-community/eslint-plugin-jest
  - jest
  # https://github.com/babel/eslint-plugin-babel
  - babel

# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  node: true
  jest: true

# https://github.com/babel/babel-eslint
parser: babel-eslint

extends:
  - 'airbnb-base'

rules:
  no-console: 0
  eqeqeq: 0
  linebreak-style: 0
  no-eval: [2, {"allowIndirect": true}] 
  # https://eslint.org/docs/rules/no-eval#options
