name: Lint-test

on: [status]

jobs:
  build:
    runs-on: ubuntu-18.04
    
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
      - uses: actions/setup-node@v1
        with:
          node-version: '13'
      - name: npm install
        run: make install
      - name: Running ESLint
        run: make lint
    