name: Lint-test

on: [push]

jobs:
  eslint-test:
    name: Running ESLint
    runs-on: ubuntu-18.04
    
    steps:
      - uses: actions/checkout@v1
      - name: npm install
        run: make install
      - name: run eslint
        run: make lint
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '13'
      - run: npm install -g yarn
      - run: yarn install
      - run: yarn build
      - uses: paambaati/codeclimate-action@v2.2.4
        env:
          CC_TEST_REPORTER_ID: 945dfb58a832d233a3caeb84e3e6d3be212e8c7abcb48117fce63b9adcb43647
        with:
          coverageCommand: yarn coverage
